{
 "title": "Observability - Pipeline Health Dashboard",
 "tags": [
  "airflow",
  "pyspark",
  "pipeline"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Airflow DAG Successful Runs Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (dag_id) (otel_airflow_ti_successes_total)",
     "legendFormat": "{{dag_id}} - Successes"
    }
   ]
  },
  {
   "title": "Airflow DAG Failed Runs Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (dag_id) (otel_airflow_ti_failures_total)",
     "legendFormat": "{{dag_id}} - Failures"
    }
   ]
  },
  {
   "title": "PySpark Batch Job Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pyspark_job_duration_seconds", "legendFormat": "{{job_name}} - Duration" }
   ]
  },
  {
   "title": "PySpark Batch Processed Records Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pyspark_job_records_processed_total",
     "legendFormat": "{{job_name}} - Records"
    }
   ]
  }
 ]
}